FROM centos:7
LABEL AUTHOR=vmarkau
RUN yum install -y httpd web-assets-httpd && \
yum clean all
RUN echo "Student: vitali markau" > /var/www/html/index.html 
EXPOSE 80
ENTRYPOINT ["httpd"]
CMD ["-DFOREGROUND"]
